Repository MUCH-MORE-MONEY/iOS, pull requests merged in 2023-09, with the labels that each got.

#97 [Feat] 통계 카테고리 Bar chart
  MMM/Sources/ViewController/Statistics/Views/StatisticsCategoryView.swift
Labels: 📈 통계

#99 [Feat] Segmented control
  MMM.xcodeproj/project.pbxproj
  MMM/Sources/ViewController/Category/CategoryViewController.swift
  MMM/Sources/ViewController/Category/Views/CategorySegmentedControl.swift
  MMM/Sources/ViewController/Statistics/StatisticsViewController.swift
  MMM/Sources/ViewController/Statistics/Views/StatisticsActivityView.swift
  MMM/Sources/ViewController/TabBar/TabBarController.swift
Labels: 📈 통계

#98 [Feat] 푸쉬 및 네트워크
  MMM.xcodeproj/project.pbxproj
  MMM/Resources/Configuration/Constants.swift
  MMM/Resources/Extensions/Ex+Date.swift
  MMM/Resources/Extensions/Ex+String.swift
  MMM/Sources/Models/ModelType.swift
  MMM/Sources/Models/Requests/PushRequest.swift
  MMM/Sources/Models/Responses/PushResponse.swift
  MMM/Sources/Reactor/PushSettingDetailReactor.swift
  MMM/Sources/Reactor/PushSettingReactor.swift
  MMM/Sources/Services/Network/APIType.swift
  MMM/Sources/Services/Network/MMMAPIService.swift
  MMM/Sources/Services/Network/NetworkProtocol.swift
  MMM/Sources/Utilities/RxOperation.swift
  MMM/Sources/ViewController/Challenge/ChallengeViewController.swift
  MMM/Sources/ViewController/Home/DatePicker2ViewController.swift
  MMM/Sources/ViewController/Profile/PushSettingDetailViewController.swift
  MMM/Sources/ViewController/Profile/PushSettingViewController.swift
  MMM/Sources/ViewController/Profile/Views/PushSetting/DetailTimeSettingView.swift
  MMM/Sources/ViewController/Profile/Views/PushSetting/TextSettingView.swift
  MMM/Sources/ViewController/Profile/Views/PushSetting/TimeSettingView.swift
  MMM/Sources/ViewController/Profile/Views/PushSetting/Week/WeekCollectionHeaderView.swift
  MMM/Sources/ViewController/Profile/Views/PushSetting/Week/WeekCollectionViewCell.swift
  MMM/Sources/ViewController/TabBar/TabBarController.swift
  Podfile
  Podfile.lock
Labels: 📡 Network, 🔔 Push

#102 [Hotfix] Timer로 selectRow가 실행되어 앱이 종료되는 문제 해결
  MMM/Sources/ViewController/Statistics/StatisticsViewController.swift
  MMM/Sources/ViewController/Statistics/Views/StatisticsActivityView.swift
Labels: bug, 📈 통계

#109 [Hotfix] Merge후 Code error 해결
  MMM/Sources/Reactor/BottomSheetReactor.swift
  MMM/Sources/Services/Network/MMMAPIService.swift
  MMM/Sources/ViewController/Home/DatePicker2ViewController.swift
  MMM/Sources/ViewController/Profile/PushSettingDetailViewController.swift
Labels: bug

#111 [Feat] 통계 메인 API 및 UI 완성
  MMM.xcodeproj/project.pbxproj
  MMM/Resources/Assets/Color.xcassets/Gray Scale/gray800.colorset/Contents.json
  MMM/Resources/Extensions/Ex+String.swift
  MMM/Sources/Models/CategoryBar.swift
  MMM/Sources/Models/EconomicActivity.swift
  MMM/Sources/Models/Requests/PushReqDto.swift
  MMM/Sources/Models/Responses/PushResDto.swift
  MMM/Sources/Models/Responses/StaticsticsResponse.swift
  MMM/Sources/Models/Responses/StatisticsResDto.swift
  MMM/Sources/Reactor/BottomSheet/DateBottomSheetReactor.swift
  MMM/Sources/Reactor/BottomSheet/SatisfactionBottomSheetReactor.swift
  MMM/Sources/Reactor/BottomSheetReactor.swift
  MMM/Sources/Reactor/CategoryReactor.swift
  MMM/Sources/Reactor/PushSettingDetailReactor.swift
  MMM/Sources/Reactor/StatisticsReactor.swift
  MMM/Sources/Services/Network/APIType.swift
  MMM/Sources/Services/Network/MMMAPIService.swift
  MMM/Sources/Services/ProfileProvider.swift
  MMM/Sources/Services/ServiceProvider.swift
  MMM/Sources/Services/StatisticsProvider.swift
  MMM/Sources/ViewController/BottomSheet/BottomSheetViewController2.swift
  MMM/Sources/ViewController/BottomSheet/DateBottomSheetViewController.swift
  MMM/Sources/ViewController/BottomSheet/SatisfactionBottomSheetViewController.swift
  MMM/Sources/ViewController/ETC./CustomRefreshControl.swift
  MMM/Sources/ViewController/ETC./StarPickerViewController.swift
  MMM/Sources/ViewController/Home/HomeViewController.swift
  MMM/Sources/ViewController/Home/Views/HomeTableViewCell.swift
  MMM/Sources/ViewController/Profile/PushSettingDetailViewController.swift
  MMM/Sources/ViewController/Profile/PushSettingViewController.swift
  MMM/Sources/ViewController/Statistics/StatisticsViewController.swift
  MMM/Sources/ViewController/Statistics/Views/StatisticsActivityTableViewCell.swift
  MMM/Sources/ViewController/Statistics/Views/StatisticsActivityView.swift
  MMM/Sources/ViewController/Statistics/Views/StatisticsAverageView.swift
  MMM/Sources/ViewController/Statistics/Views/StatisticsCategoryView.swift
  MMM/Sources/ViewController/Statistics/Views/StatisticsSatisfactionListView.swift
  MMM/Sources/ViewController/Statistics/Views/StatisticsSatisfactionView.swift
  MMM/Sources/ViewController/Statistics/Views/StatisticsTitleView.swift
  MMM/Sources/ViewController/TabBar/TabBarController.swift
Labels: 📈 통계

#117 [Feat] 카테고리 편집 디테일 부분
  MMM.xcodeproj/project.pbxproj
  MMM/Resources/Assets/Icon.xcassets/iconMinus16.imageset/Contents.json
  MMM/Resources/Assets/Icon.xcassets/iconPlus16.imageset/Contents.json
  MMM/Resources/Extensions/Ex+UICollectionView.swift
  MMM/Resources/Extensions/Ex+UIImage.swift
  MMM/Resources/Extensions/Ex+UITextField.swift
  MMM/Sources/Models/CategoryEdit.swift
  MMM/Sources/Models/CategoryEditSectionModel.swift
  MMM/Sources/Reactor/BottomSheet/CategoryEditBottomSheetReactor.swift
  MMM/Sources/Reactor/CategoryEditCollectionViewCellReactor.swift
  MMM/Sources/Reactor/CategoryEditReactor.swift
  MMM/Sources/Reactor/CategoryReactor.swift
  MMM/Sources/Services/CategoryProvider.swift
  MMM/Sources/Services/ServiceProvider.swift
  MMM/Sources/ViewController/BottomSheet/CategoryEditBottomSheetViewController.swift
  MMM/Sources/ViewController/Category/CategoryContentViewController.swift
  MMM/Sources/ViewController/Category/CategoryViewController.swift
  MMM/Sources/ViewController/Category/Views/CategorySectionHeader.swift
  MMM/Sources/ViewController/CategoryEdit/CategoryEditViewController.swift
  MMM/Sources/ViewController/CategoryEdit/Views/CategoryEditCollectionViewCell.swift
  MMM/Sources/ViewController/CategoryEdit/Views/CategoryEditSectionFooter.swift
  MMM/Sources/ViewController/CategoryEdit/Views/CategoryEditSectionHeader.swift
Labels: 📈 통계
