Repository MUCH-MORE-MONEY/iOS, pull requests merged in 2024-02, with the labels that each got.

#172 [Feat] 에산 View - 1
  MMM.xcodeproj/project.pbxproj
  MMM/Resources/Assets/Icon.xcassets/iconCharacterBudget.imageset/Contents.json
  MMM/Resources/Assets/Icon.xcassets/iconCharacterBudget.imageset/iconCharacterBudget.png
  MMM/Resources/Assets/Icon.xcassets/iconCharacterBudget.imageset/iconCharacterBudget@2x.png
  MMM/Resources/Assets/Icon.xcassets/iconCharacterBudget.imageset/iconCharacterBudget@3x.png
  MMM/Resources/Base/BaseAddActivityViewController.swift
  MMM/Resources/Extensions/UIKit/Ex+Icon.swift
  MMM/Sources/Reactor/StatisticsReactor.swift
  MMM/Sources/ViewController/Statistics/StatisticsViewController.swift
  MMM/Sources/ViewController/Statistics/Views/StatisticsAverageView.swift
  MMM/Sources/ViewController/Statistics/Views/StatisticsNewTitleView.swift
Labels: 📈 통계

#176 [Fix] 앱이 꺼지는 문제 - Caterory edit의 Out of index 해결
  MMM.xcodeproj/project.pbxproj
  MMM/Sources/ViewController/CategoryEdit/CategoryEditViewController.swift
  MMM/Sources/ViewController/CategoryEdit/Views/CategoryEditSectionFooter.swift
Labels: bug, 📈 통계

#177 [Feat] 카메라 선택접근 오류 개선
  MMM/Resources/Base/BaseAddActivityViewController.swift
  MMM/Resources/Extensions/Ex+UIImageView.swift
  MMM/Sources/ViewController/HomeDetail/DetailViewController.swift
  MMM/Sources/ViewController/HomeDetail/Edit/EditActivityViewController.swift
Labels: bug
